# Generated by Django 5.1.2 on 2026-04-13 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0001_initial'),
        ('utilisateur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avi',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.client'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='licence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.licence'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='utilisateurs',
            field=models.ManyToManyField(blank=True, related_name='entreprises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depense',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='client',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='entrer',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.client'),
        ),
        migrations.AddField(
            model_name='factentre',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='factsortie',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='historiqueentrer',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.client'),
        ),
        migrations.AddField(
            model_name='historiqueentrer',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='historiqueentrer',
            name='entrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.entrer'),
        ),
        migrations.AddField(
            model_name='historiqueentrer',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquesortie',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.client'),
        ),
        migrations.AddField(
            model_name='historiquesortie',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='historiquesortie',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiemententreprise',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiemententreprise',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.client'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sortie',
            name='entrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entrer'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties', to='entreprise.facture'),
        ),
        migrations.AddField(
            model_name='historiquesortie',
            name='sortie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.sortie'),
        ),
        migrations.AddField(
            model_name='souscategorie',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.categorie'),
        ),
        migrations.AddField(
            model_name='entrer',
            name='souscategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.souscategorie'),
        ),
        migrations.AddField(
            model_name='commande',
            name='souscategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.souscategorie'),
        ),
    ]
