# Generated by Django 5.1.2 on 2025-11-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_sortie_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueentrer',
            name='ancien_qte',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
