# Generated by Django 5.1.2 on 2025-11-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0003_historiqueentrer_ancien_qte'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueentrer',
            name='cumuler_qe',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
