# Generated by Django 5.1.2 on 2025-12-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0004_historiqueentrer_cumuler_qe'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
