# Generated by Django 5.1.2 on 2025-12-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0005_entrer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrer',
            name='description',
        ),
    ]
