# Generated by Django 5.1.2 on 2025-12-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0006_remove_entrer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueentrer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
