# Generated by Django 5.1.2 on 2025-12-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0007_historiqueentrer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquesortie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
