# Generated by Django 5.1.2 on 2025-12-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0008_historiquesortie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrer',
            name='qte_critique',
            field=models.IntegerField(default=0),
        ),
    ]
