# Generated by Django 5.1.2 on 2025-12-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0010_alter_entrer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueentrer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
