# Generated by Django 5.1.2 on 2026-01-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0011_alter_historiqueentrer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='remise_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
