# Generated by Django 5.1.2 on 2026-01-04 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0012_sortie_remise_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueentrer',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.client'),
        ),
        migrations.AddField(
            model_name='historiquesortie',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.client'),
        ),
    ]
