# Generated by Django 5.1.2 on 2026-01-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0013_historiqueentrer_client_historiquesortie_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueentrer',
            name='pu_achat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
