# Generated by Django 5.1.2 on 2026-01-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0014_historiqueentrer_pu_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrer',
            name='unite',
            field=models.CharField(choices=[('litre', 'Litre'), ('kilos', 'Kilos'), ('mètres', 'Mètres')], default='kilos', max_length=20),
        ),
        migrations.AddField(
            model_name='historiqueentrer',
            name='unite',
            field=models.CharField(choices=[('litre', 'Litre'), ('kilos', 'Kilos'), ('mètres', 'Mètres')], default='kilos', max_length=20),
        ),
        migrations.AddField(
            model_name='historiquesortie',
            name='unite',
            field=models.CharField(choices=[('litre', 'Litre'), ('kilos', 'Kilos'), ('mètres', 'Mètres')], default='kilos', max_length=20),
        ),
        migrations.AddField(
            model_name='sortie',
            name='unite',
            field=models.CharField(choices=[('litre', 'Litre'), ('kilos', 'Kilos'), ('mètres', 'Mètres')], default='kilos', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrer',
            name='qte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='entrer',
            name='qte_critique',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historiqueentrer',
            name='ancien_qte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historiqueentrer',
            name='qte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historiquesortie',
            name='qte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='qte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
