# Generated by Django 5.1.2 on 2026-04-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='email_user',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Editor'), (3, 'Author'), (4, 'Visitor')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='typeRole',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Simple'), (2, 'Basic'), (3, 'Premium')], default=3),
        ),
    ]
