# Generated by Django 5.1.2 on 2025-08-18 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_utilisateur_created_cab_utilisateur_is_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
