# Generated by Django 5.1.2 on 2025-09-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_alter_utilisateur_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cra'), (2, 'Basic'), (3, 'Premium')], default=1),
        ),
    ]
