# Generated by Django 5.1.2 on 2025-09-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_alter_licence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Essai'), (2, 'Standard'), (3, 'Premium')], default=1),
        ),
    ]
