# Generated by Django 5.1.2 on 2026-01-02 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_alter_licence_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_start', models.PositiveSmallIntegerField()),
                ('day_end', models.PositiveSmallIntegerField()),
                ('hour_start', models.TimeField()),
                ('hour_end', models.TimeField()),
                ('active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
