# Generated by Django 5.1.2 on 2026-01-03 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_rolerestriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerestriction',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restriction', to=settings.AUTH_USER_MODEL),
        ),
    ]
