# Generated by Django 5.1.2 on 2026-01-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0007_alter_rolerestriction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='typeRole',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Simple'), (2, 'Basic'), (3, 'Prenium')], null=True),
        ),
        migrations.AlterField(
            model_name='licence',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Stock Simple'), (2, 'Stock Pro'), (3, 'Stock Premium')], default=1),
        ),
    ]
