# Generated by Django 5.1.2 on 2026-01-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0008_utilisateur_typerole_alter_licence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='typeRole',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Simple'), (2, 'Basic'), (3, 'Prenium')], default=2),
        ),
    ]
