# Generated by Django 5.1.2 on 2026-01-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0009_alter_utilisateur_typerole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='typeRole',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Simple'), (2, 'Basic'), (3, 'Premium')], default=2),
        ),
    ]
